insert into lord_of_the_rings values (11, 'Aragorn', 'King of Gondor',178);
insert into lord_of_the_rings values (12, 'Legolas', 'Elph archer', 194);
insert into lord_of_the_rings values (13, 'Frodo', 'The Hobbit', 134);
insert into lord_of_the_rings values (14, 'Gimli', 'Dwarf with big Axe and Heart', 125);
insert into lord_of_the_rings values (15, 'Boromir', 'The traitor', 170);
insert into lord_of_the_rings values (16, 'Sauron', 'The Evil', 230);
insert into lord_of_the_rings values (17, 'Gandalf', 'Wise Wizard', 200);
insert into lord_of_the_rings values (18, 'Saruman', 'Evil wizard', 198);
insert into lord_of_the_rings values (19, 'Teoden', 'King of Rohan', 180);
insert into lord_of_the_rings values (110, 'Eowyn', 'Douther of Teoden', 168);

insert into full_stack values (21, 'Vadim', 'Garem master with a blaster', 180);
insert into full_stack values (22, 'Eledriel', 'aka Elektrodrel, princess of light elves', 180);
insert into full_stack values (23, 'Larine', 'Princess of dark elves', 180);
insert into full_stack values (24, 'Miril', 'Vampyre queen', 176);
insert into full_stack values (25, 'Narin', 'Dwarf master of an anecdote', 120);
insert into full_stack values (26, 'Zara', 'Commander of Mithril dragon', 160);
insert into full_stack values (27, 'Lirmiliel', 'Awake after some time...', 190);
insert into full_stack values (28, 'Anzha', 'She doesn''t know who she is', 178);
insert into full_stack values (29, 'Irkana', 'Dragon menestrel', 185);
insert into full_stack values (210, 'Kraboramidur', 'aka Krabodurrr', 210);

insert into overlord values (31, 'Momonga', 'The greatest evil wich does not want to be evil', 200);
insert into overlord values (32, 'Albedo', 'Beautiful, but bitch', 190);
insert into overlord values (33, 'Shaltir', 'High Vampyre-necrofil', 140);
insert into overlord values (34, 'Cocytus', 'Honorable warrior', 210);
insert into overlord values (35, 'Demiurg', 'Genius demon in shadows', 190);
insert into overlord values (36, 'Fluder Paradine', 'Ment to be greatest mage in the world', 165);
insert into overlord values (37, 'PLD', 'For those who know', 210);
insert into overlord values (38, 'Brein unglaus', 'Master of manicure', 180);
insert into overlord values (39, 'Gazeph Stronov', 'A devoted heart comes from the people', 185);
insert into overlord values (310, 'Neia Baracha', 'A doomed heart comes from the people', 170);

insert into races values (1, 180, 100, 'Man');
insert into races values (2, 200, 5000, 'Elf');
insert into races values (3, 130, 100, 'Dwarf');
insert into races values (4, 180, 150, 'Tifling/succubus');
insert into races values (5, 180, 100000000, 'Demon');
insert into races values (6, 180, 100000000, 'Vampyre');
insert into races values (7, 130, 100, 'Hobbit');
insert into races values (8, 250, 1000, 'Dragon');
insert into races values (9, 200, 300, 'Insectoid');
insert into races values (10, 200, 100000000, 'Undead');

insert into characters_races values (11, 1);
insert into characters_races values (12, 2);
insert into characters_races values (13, 7);
insert into characters_races values (14, 3);
insert into characters_races values (15, 1);
insert into characters_races values (16, 2);
insert into characters_races values (17, 1);
insert into characters_races values (18, 1);
insert into characters_races values (19, 1);
insert into characters_races values (110, 1);
insert into characters_races values (21, 1);
insert into characters_races values (22, 2);
insert into characters_races values (23, 2);
insert into characters_races values (24, 6);
insert into characters_races values (25, 3);
insert into characters_races values (26, 1);
insert into characters_races values (27, 2);
insert into characters_races values (28, 4);
insert into characters_races values (29, 8);
insert into characters_races values (210, 8);
insert into characters_races values (31, 10);
insert into characters_races values (32, 4);
insert into characters_races values (33, 6);
insert into characters_races values (34, 9);
insert into characters_races values (35, 5);
insert into characters_races values (36, 1);
insert into characters_races values (37, 8);
insert into characters_races values (38, 1);
insert into characters_races values (39, 1);
insert into characters_races values (310, 1);

insert into classes values (1, 'Tank', 'Warrior');
insert into classes values (2, 'Dps', 'Archer');
insert into classes values (3, 'Support', 'Wizard');
insert into classes values (4, 'Dps', 'Rogue');
insert into classes values (5, 'Dps', 'Caster');


insert into characters_classes values (11, 1);
insert into characters_classes values (12, 2);
insert into characters_classes values (13, 4);
insert into characters_classes values (14, 1);
insert into characters_classes values (15, 1);
insert into characters_classes values (16, 1);
insert into characters_classes values (17, 3);
insert into characters_classes values (18, 5);
insert into characters_classes values (19, 1);
insert into characters_classes values (110, 1);
insert into characters_classes values (21, 1);
insert into characters_classes values (22, 2);
insert into characters_classes values (23, 4);
insert into characters_classes values (24, 1);
insert into characters_classes values (25, 1);
insert into characters_classes values (26, 1);
insert into characters_classes values (27, 5);
insert into characters_classes values (28, 4);
insert into characters_classes values (29, 3);
insert into characters_classes values (210, 1);
insert into characters_classes values (31, 5);
insert into characters_classes values (32, 1);
insert into characters_classes values (33, 1);
insert into characters_classes values (34, 1);
insert into characters_classes values (35, 3);
insert into characters_classes values (36, 3);
insert into characters_classes values (37, 1);
insert into characters_classes values (38, 1);
insert into characters_classes values (39, 1);
insert into characters_classes values (310, 2);

insert into weapons values (1, 'Melee', 'Sword');
insert into weapons values (2, 'Melee', 'Axe');
insert into weapons values (3, 'Ranged', 'Bow');
insert into weapons values (4, 'Ranged', 'Wizard staff');
insert into weapons values (5, 'Defensive', 'Shield');
insert into weapons values (6, 'Ranged', 'Blaster');
insert into weapons values (7, 'Melee', 'Daggers');
insert into weapons values (8, 'Defensive', 'Mace');
insert into weapons values (9, 'Melee', 'Spear');

insert into characters_weapons values (11, 1);
insert into characters_weapons values (12, 3);
insert into characters_weapons values (13, 7);
insert into characters_weapons values (14, 2);
insert into characters_weapons values (15, 1);
insert into characters_weapons values (15, 5);
insert into characters_weapons values (16, 8);
insert into characters_weapons values (17, 4);
insert into characters_weapons values (18, 4);
insert into characters_weapons values (19, 1);
insert into characters_weapons values (110, 9);
insert into characters_weapons values (21, 6);
insert into characters_weapons values (22, 3);
insert into characters_weapons values (23, 3);
insert into characters_weapons values (23, 7);
insert into characters_weapons values (24, 1);
insert into characters_weapons values (25, 2);
insert into characters_weapons values (26, 1);
insert into characters_weapons values (28, 7);
insert into characters_weapons values (31, 4);
insert into characters_weapons values (32, 2);
insert into characters_weapons values (33, 9);
insert into characters_weapons values (34, 1);
insert into characters_weapons values (34, 2);
insert into characters_weapons values (36, 4);
insert into characters_weapons values (37, 1);
insert into characters_weapons values (37, 2);
insert into characters_weapons values (37, 9);
insert into characters_weapons values (37, 5);
insert into characters_weapons values (38, 1);
insert into characters_weapons values (39, 1);
insert into characters_weapons values (310, 3);

insert into classes_weapon_types values (1, 1);
insert into classes_weapon_types values (1, 5);
insert into classes_weapon_types values (1, 2);
insert into classes_weapon_types values (2, 3);
insert into classes_weapon_types values (3, 4);
insert into classes_weapon_types values (2, 6);
insert into classes_weapon_types values (1, 8);
insert into classes_weapon_types values (1, 9);
insert into classes_weapon_types values (4, 7);
insert into classes_weapon_types values (4, 3);
insert into classes_weapon_types values (5, 4);
